<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/10/19 21:48:33
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
