<?php
// auto-generated by sfViewConfigHandler
// date: 2009/10/19 22:08:06
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $this->setComponentSlot('lateral', 'usuario', 'logueo');
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set component "%s" (%s/%s)', 'lateral', 'usuario', 'logueo'))));
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'TCU Educación para el Manejo de Desechos', false, false);

  $response->addStylesheet('estilo.css', '', array ());
  $response->addStylesheet('thickbox.css', '', array ());
  $response->addJavascript('jquery-1.3.2.min.js', '', array ());
  $response->addJavascript('kwicks.js', '', array ());
  $response->addJavascript('custom.js', '', array ());
  $response->addJavascript('tab.js', '', array ());
  $response->addJavascript('jquery.validate.min.js', '', array ());
  $response->addJavascript('thickbox.js', '', array ());


