<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/10/19 22:08:06
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
