generator:
  class: sfPropelGenerator
  param:
    model_class:           Tipo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tipo
    with_propel_route:     1

    config:
      actions: ~
      fields:
        imagen: {  label: Imágen, help: Se recomiendan imágenes de menos de 250 x 250 pixeles }
      list:
        title: Secciones
        display: [=id, =nombre]
        max_per_page: 10
        batch_actions: {}
        actions:  {}
        object_actions:
          _edit:      { label: Editar }
      filter:
          class: false
      form:
          display: [nombre, imagen]
      edit:
        title: Edición de "%%nombre%%"
        actions:
          _list: { label: Cancelar }
          _save:   { label: Guardar }
      new:     ~
