<?php
// auto-generated by sfRoutingConfigHandler
// date: 2009/10/19 21:53:06
return array(
'subseccion' => new sfPropelRouteCollection(array (
  'model' => 'Subseccion',
  'module' => 'subseccion',
  'prefix_path' => 'subseccion',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'subseccion',
  'requirements' => 
  array (
  ),
)),
'tipo' => new sfPropelRouteCollection(array (
  'model' => 'Tipo',
  'module' => 'tipo',
  'prefix_path' => 'tipo',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'tipo',
  'requirements' => 
  array (
  ),
)),
'seccion' => new sfPropelRouteCollection(array (
  'model' => 'Seccion',
  'module' => 'seccion',
  'prefix_path' => 'seccion',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'seccion',
  'requirements' => 
  array (
  ),
)),
'tcu' => new sfPropelRouteCollection(array (
  'model' => 'Tcu',
  'module' => 'tcu',
  'prefix_path' => 'tcu',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'tcu',
  'requirements' => 
  array (
  ),
)),
'enlace' => new sfPropelRouteCollection(array (
  'model' => 'Enlace',
  'module' => 'enlace',
  'prefix_path' => 'enlace',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'enlace',
  'requirements' => 
  array (
  ),
)),
'sitio' => new sfPropelRouteCollection(array (
  'model' => 'Sitio',
  'module' => 'sitio',
  'prefix_path' => 'sitio',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'sitio',
  'requirements' => 
  array (
  ),
)),
'encargado' => new sfPropelRouteCollection(array (
  'model' => 'Encargado',
  'module' => 'encargado',
  'prefix_path' => 'encargado',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'encargado',
  'requirements' => 
  array (
  ),
)),
'persona' => new sfPropelRouteCollection(array (
  'model' => 'Persona',
  'module' => 'persona',
  'prefix_path' => 'persona',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'persona',
  'requirements' => 
  array (
  ),
)),
'homepage' => new sfRoute('/', array (
  'module' => 'inicio',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
