<?php
// auto-generated by sfViewConfigHandler
// date: 2009/10/19 21:53:28
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Administración', false, false);

  $response->addStylesheet('/sfPropelPlugin/css/global.css', '', array ());
  $response->addStylesheet('menu_tab.css', '', array ());
  $response->addStylesheet('admin.css', '', array ());
  $response->addJavascript('jquery-1.3.2.min.js', '', array ());
  $response->addJavascript('kwicks.js', '', array ());
  $response->addJavascript('custom.js', '', array ());
  $response->addJavascript('tab.js', '', array ());
  $response->addJavascript('jquery.validate.min.js', '', array ());


