default:
  http_metas:
    content-type: text/html

  metas:
    title:        Administración
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [/sfPropelPlugin/css/global.css, menu_tab.css ,admin.css]

  javascripts:    []

  has_layout:     on
  layout:         layout
