generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_propel_route:     1

    config:
      actions: ~
      fields:
        is_super_admin: { label: "¿Es Administrador?", help: Si el usuario tiene todos los permisos o no }
        is_active: { label: "¿Está activo?", help: Si este usuario está activo o no }
        password: { label: "Contraseña" }
        username: { label: "Usuario" }
        created_at: { label: "Creado en" }
        last_login: { label: "Último Ingreso" }
        password_again: { label: "Contraseña (de nuevo)" }

      list:
        title:   Lista de Usuarios
        display: [=username, created_at, last_login]
      filter:
        class:    false
                
      form:
        class: sfGuardUserAdminForm
        display:
          "NONE":                   [username, password, password_again]
          "Permissions and groups": [is_active, is_super_admin, sf_guard_user_group_list, sf_guard_user_permission_list]

      edit:
        title: Editar Usuario "%%username%%"

      new:
        title: Nuevo Usuario
