default:
  http_metas:
    content-type: text/html

  metas:
    title:        TCU Educación para el Manejo de Desechos
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [estilo.css,thickbox.css ]

  javascripts:    [jquery-1.3.2.min.js,kwicks.js,custom.js,tab.js,jquery.validate.min.js,thickbox.js]

  has_layout:     on
  layout:         layout

  components:
    lateral:  [usuario, logueo]

